# Generated by Django 3.0.2 on 2020-04-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_first_name', models.CharField(max_length=30)),
                ('about_second_name', models.CharField(max_length=30)),
                ('about_address', models.TextField(max_length=300)),
                ('about_mobile_number', models.CharField(max_length=10)),
                ('about_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
