# Generated by Django 3.0.2 on 2020-04-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_aboutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='about_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
