# Generated by Django 3.0.2 on 2020-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_aboutinfo_about_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('role_description', models.TextField(max_length=1000)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
    ]
