# Generated by Django 3.0.2 on 2020-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=30, null=True)),
                ('university', models.CharField(blank=None, max_length=30)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True)),
            ],
        ),
    ]
