# Generated by Django 3.0.2 on 2020-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_auto_20200401_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
