# Generated by Django 3.0.2 on 2020-04-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0007_auto_20200401_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
