# Generated by Django 3.0.2 on 2020-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0008_education_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
